### PR TITLE
RU language

### PR DESCRIPTION
**Pull request by Vaultleaper**
As Russian isn't my native language, it should be correct, but it would be nice if it can get checked. I have checked it and it seems correct.

### CODE REVIEW

**Comment by Vaults1** [comment]
I don't know why the extra commits are appearing..

**Comment by k3ithos** [comment]
Conflicts...

**Comment by NIIP99** [comment]
Well, have no idea how to solve this conflict... @keithkfng Can u help? xD :p

**Comment by k3ithos** [comment]
@UltimateMcraft - try pulling OUR changes? Or maybe you'll have to recommit again...

**Comment by remotevase** [comment]
I pretty sure i know how. Delete the existing lang-ru.yml file and then it should be fixed

**Comment by Vaults1** [comment]
Try that, if it doesn't work paste the below file and close this.

```
---
# Russian Language File
# (c) 2016 All rights reserved, Plugswork.
# Thanks to @UltimateMcraft for the Russian translation!
version: 1.0
lang: EN
main:
  selectConsoleLang: ". Пожалуйста, выберите язык консоли [EN / CN]"
  enterServerID: "Пожалуйста, введите идентификатор сервера."
  enterSecretKey: "Пожалуйста, введите секретный ключ."
  pwTerms: "С помощью этого плагина, вы соглашаетесь с Plugswork Условия."
  pwTermsAgree: "Вы принимаете Условия Plugswork [Y / N]?"
  pwTermsError: "Вы должны принять Plugswork Условия использования Plugswork услуг и продуктов."
  invalidProvider: "Invalid поставщик выбран в config.yml!"
  donateNote: "Пожертвуйте нам по телефону (plugswork.com/donate), чтобы поддержать нас!"
  runAsPlayer: "Пожалуйста, запустите эту команду в качестве игрока"
  reloading: "перегрузочный Settings ..."
  reloadSucessful: "Настройки были успешно перезагружена"
api:
  openError: "Ошибка Open API СВЕРШИВШИМСЯ \n %0%"
  emptyDataError: "Неверный ID сервера или Секретный ключ, пожалуйста, проверьте на панели управления, если вы заполнили в правильном ID и ключ."
  serverIDError: "Неверный ИД сервера, пожалуйста, проверьте, если вы заполнили в правильном ID сервера"
  sKeyError: "Invalid Секретный ключ, пожалуйста, проверьте, если вы в заполнены правильно секретный ключ."
  ValidationError: "Мы не можем распознать этот сервер, пожалуйста, проверьте, если IP, порт и т.д. такое же с данными заполненной на панели управления."
...
```

**Comment by Vaults1** [comment]
I see it's done.

**Pull request closed without merging**
