### PR TITLE
Travis build almost working

### PR DESCRIPTION
**Pull request by k3ithos**
Just a few more things needed to configure and some errors to solve :)

### CODE REVIEW

**Comment by NIIP99** [comment]
Okay :) Hope it can be solved soon :P

**Comment by k3ithos** [comment]
@deotern :)

**Comment by NIIP99** [comment]
@keithkfng How about the gh-branch? Whats that branch for?

**Comment by k3ithos** [comment]
@deotern that's only for hosting the phar files so people can download them

**Pull request merged**
